### PR TITLE
Change to approved status

### PR DESCRIPTION
**Pull request by TelegramSam**
Pending WG, TSC, and SC approval.

### CODE REVIEW

**Comment by andorsk** [comment]
To discuss tomorrow at the TSC meeting. No problems on my end pending discussion.

**Comment by mccown** [comment]
I support this change in status

**Comment by Eldersonar** [comment]
@andorsk any news on when it will get reviewed/approved?

**Review by Eldersonar — APPROVED** [review]
Approved on my end

**Comment by andorsk** [comment]
This was approved by the tsc. Sorry! I mentioned it to Sam but I should have pinged this PR. 

You're good to go!

**Review by andorsk — APPROVED** [review]

**Comment by andorsk** [comment]
Merged the PR in. Thanks @kimdhamilton. Congrats everyone.

**Pull request merged**
