### PR TITLE
Adds external governance links

### LINKED ISSUE #9: Links to other Credential Trust Establishment docs?
This could be used to reference which docs are trusted by this doc, to allow for hierarchal structures. Thoughts?

### PR DESCRIPTION
**Pull request by TelegramSam**
Fixes #9

### CODE REVIEW

**Comment by TelegramSam** [comment]
needs some context about cascading `trusted_governance` links

**Comment by TelegramSam** [comment]
needs hashlink or other method to make sure the file you pull is verified? maybe include the publishing DID?

**Comment by TelegramSam** [comment]
needs discussion of trust implications by publisher  when external governance is linked to.

**Comment by TelegramSam** [comment]
Discussed WG 20230925. No objections to merging.

**Comment by andorsk** [comment]
@TelegramSam do you need some help merging this?

**Review by andorsk — APPROVED** [review]
LGTM. Discussed on DIF call and helping approve this merge!

**Pull request merged**
